### Register a new ADMIN
POST http://localhost:8080/api/admins/register
Content-Type: application/json

{
  "email": "admin@resapp.com",
  "phone": "123-456-7890",
  "password": "adminpassword",
  "firstName": "Admin",
  "lastName": "ResApp"
}

### Register a new CUSTOMER
POST http://localhost:8080/api/customers/register
Content-Type: application/json

{
  "email": "egemen@sfu.ca",
  "phone": "111-222-333",
  "password": "e@123456",
  "firstName": "Egemen",
  "lastName": "Guney"
}

### Register a new CUSTOMER
POST http://localhost:8080/api/customers/register
Content-Type: application/json

{
  "email": "a@email.com",
  "phone": "222-333-444",
  "password": "a@123456",
  "firstName": "a",
  "lastName": "A"
}

### Register a new CUSTOMER
POST http://localhost:8080/api/customers/register
Content-Type: application/json

{
  "email": "b@email.com",
  "phone": "333-444-555",
  "password": "b@123456",
  "firstName": "b",
  "lastName": "B"
}

### Register a new RESTAURANT
POST http://localhost:8080/api/restaurants/register
Content-Type: application/json

{
  "email": "owner@bobsburgers.com",
  "phone": "999-888-777",
  "password": "burgerpassword",
  "name": "Bob's Burgers",
  "busPhone": "999-0001",
  "stars": 4.5,
  "openingHours": "09:00:00",
  "closingHours": "22:00:00",
  "isOpen": true,
  "street": "123 Ocean Avenue",
  "city": "Seymour's Bay",
  "state": "NJ",
  "zipCode": "08260",
  "country": "USA"
}

### Register a new RESTAURANT
POST http://localhost:8080/api/restaurants/register
Content-Type: application/json

{
  "email": "owner@dominospizza.com",
  "phone": "888-777-666",
  "password": "pizzapassword",
  "name": "Domino's Pizza",
  "busPhone": "888-0001",
  "stars": 4.5,
  "openingHours": "09:00:00",
  "closingHours": "22:00:00",
  "isOpen": true,
  "street": "234 Sea Avenue",
  "city": "Vancouver",
  "state": "BC",
  "zipCode": "V5A 0X0",
  "country": "Canada"
}

### Register a new RESTAURANT
POST http://localhost:8080/api/restaurants/register
Content-Type: application/json

{
  "email": "owner@chipotle.com",
  "phone": "777-666-555",
  "password": "tacopassword",
  "name": "Chipotle",
  "busPhone": "777-0001",
  "stars": 4.5,
  "openingHours": "09:00:00",
  "closingHours": "22:00:00",
  "isOpen": true,
  "street": "345 Beach Avenue",
  "city": "Mexico City",
  "state": "MX",
  "zipCode": "M1X 0X0",
  "country": "Mexico"
}