### Register a New Customer
POST http://localhost:8080/api/customers/register
Content-Type: application/json

{
  "email": "egemen@sfu.ca",
  "phone": "555-0100",
  "password": "supersecretpassword",
  "firstName": "Egemen",
  "lastName": "Guney"
}

### Register a New Restaurant
POST http://localhost:8080/api/restaurants/register
Content-Type: application/json

{
  "email": "owner@bobsburgers.com",
  "phone": "555-0101",
  "password": "burgerpassword",
  "name": "Bob's Burgers",
  "busPhone": "555-0102",
  "stars": 4.5,
  "openingHours": "09:00:00",
  "closingHours": "22:00:00",
  "isOpen": true,
  "street": "123 Ocean Avenue",
  "city": "Seymour's Bay",
  "state": "NJ",
  "zipCode": "08260",
  "country": "USA"
}

### Login Test (With Phone)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "emailOrPhone": "555-0100",
  "password": "supersecretpassword"
}

### Login Test (With Email)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "emailOrPhone": "owner@bobsburgers.com",
  "password": "burgerpassword"
}

### Login Test (With Wrong Email)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "emailOrPhone": "notowner@bobsburgers.com",
  "password": "burgerpassword"
}

### Login Test (With Wrong Password)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "emailOrPhone": "555-0100",
  "password": "secretpassword"
}

### Add a Burger to the Menu
POST http://localhost:8080/api/menus/ed1ee242-265e-43ef-9976-8eab7b9448b9/items
Content-Type: application/json

{
  "name": "Classic Cheeseburger",
  "description": "Quarter pound beef patty with cheddar cheese, lettuce, and tomato.",
  "category": "Handhelds",
  "price": 12.99,
  "isAvailable": true
}

### Get the Whole Menu
GET http://localhost:8080/api/menus/ed1ee242-265e-43ef-9976-8eab7b9448b9/items

### Update a Menu Item
PUT http://localhost:8080/api/menus/ed1ee242-265e-43ef-9976-8eab7b9448b9/items/6e8a59c5-4110-4239-b57a-a797579caacf
Content-Type: application/json

{
  "name": "Truffle Cheeseburger",
  "description": "Upgraded quarter pound beef patty with truffle mayo, caramelized onions, and swiss cheese.",
  "category": "Mains",
  "price": 16.99,
  "isAvailable": true
}

### Delete a Menu Item
DELETE http://localhost:8080/api/menus/ed1ee242-265e-43ef-9976-8eab7b9448b9/items/f7a725a9-a643-4a78-a417-e9512bb21964

### Delete a Menu Item That Belongs to Another Menu
DELETE http://localhost:8080/api/menus/ed1ee242-265e-43ef-9976-8eab7b9448b9/items/f7a725a9-a643-4a78-a417-e9512bb21964
