spring:
  application:
    name: app

  sql:
    init:
      mode: always

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/resapp_db}
    username: ${DB_USERNAME:egemen}
    password: ${MY_DB_PASSWORD:password}

  flyway:
    enabled: false

  security:
    jwt:
      # Looks for a JWT_SECRET environment variable. If not found, uses the hardcoded string for local dev.
      secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 86400000