spring:
  application:
    name: app

  sql:
    init:
      mode: always

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/resapp_db}
    username: ${DB_USERNAME:egemen}
    password: ${MY_DB_PASSWORD:password}

  flyway:
    enabled: false